### ISSUE TITLE
Syntax warning for 'is/is not' vs '==/!='

### ISSUE THREAD

**Issue by a-tyler** [awsmhacks/CrackMapExtreme#23]
Running a clean build on arch linux with python 3.8.1(arch package rev 3) following your install instructions and I am getting this out of the box:

`/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/connection.py:54: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.dc_ip is '':
/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py:802: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py:802: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py:802: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if lmhash is '' and nthash is '' and (aesKey is '' or aesKey is None) and TGT is None and TGS is None:
/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py:1564: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.args.ntds is 'vss':
/usr/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/servers/smb.py:25: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if password is not '':
`
Replacing "is not" with "!=" and "is" with "==" resolved the issue for me.

**Comment by awsmhacks** [comment]
Yeah, looks like that started showing up when going from python 3.7 to 3.8, ill get those changes pushed asap.

**Comment by awsmhacks** [comment]
hmm, digestmod in hmac may have changed in 3.8.0 as well, and may be breaking. https://bugs.python.org/issue37218  
  
Maybe use 3.7.x until i figure that out (if you are seeing a digestmod error when using smb)

**Comment by a-tyler** [comment]
Thanks for the quick update!
Yeah I am saw the digest mod issue. Replacing 'impacket==0.9.20' with 'git+https://github.com/SecureAuthCorp/impacket.git' took care of that for me.

**Comment by a-tyler** [comment]
The only error that I am seeing right now is "Error getting IP Info for smb" immediately after each exec. As far as I can tell it does'nt seem to be impacting the results. It could very well be because I am using the latest impacket release just thought I would mention it all the same.
![2020-01-24-125907_3840x2160_scrot](https://user-images.githubusercontent.com/39920788/73096153-cdb7ee80-3ea9-11ea-8f73-f4d35e584eeb.png)
![2020-01-24-130405_3840x2160_scrot](https://user-images.githubusercontent.com/39920788/73096329-1d96b580-3eaa-11ea-9954-2d82edc4ed57.png)

**Comment by awsmhacks** [comment]
hmm, thats an error thrown in the [ipparser](https://github.com/awsmhacks/CrackMapExtreme/blob/master/cmx/helpers/ipparser.py) when it cant get a host by name, not sure why its showing up when listing modules or while using an IP but ill take a look. Maybe something with netaddr and python3.8  
  
also should mention that kerberoast module is busted im pretty sure, been meaning to just build it in using impackets latest and havent gotten to it yet.    
  
super thanks for reporting this stuff though!   i've been slacking on updates lately.

**Comment by awsmhacks** [comment]
using --local-auth should also work instead of specifying the domain as the hostname.  
`cmx smb x.x.x.x -u user -p pass --local-auth --shares`

**Comment by a-tyler** [comment]
Ah yeah I am hopping between testing against a dc and local auth so i just setup my scripts with a var at -d so I could reuse the same command.
Found some more issues running some of the Multi-execution commands.
It looks like the domain controller address either isn't being detected or it just isn't being handled correctly (could be my git rev of impacket).
Running cmx without a domain controller supplied on the command line like this:
`cmx smb 192.168.11.18 -d testdomain -u andrew -p YkCcNoiZJDq4aZW --users`
Returns this:
`DEBUG failed connect [Errno Connection error (testdomain.local:445)] [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/nmb.py", line 897, in _setup_connection
    af, socktype, proto, canonname, sa = socket.getaddrinfo(peer[0], peer[1], 0, socket.SOCK_STREAM)[0]
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/gevent/_socketcommon.py", line 218, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 307, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 297, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 277, in gevent._event.AsyncResult._raise_exception
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/gevent/threadpool.py", line 120, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb/ENUM/domainenum.py", line 180, in users1
    dce.connect()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/dcerpc/v5/rpcrt.py", line 800, in connect
    return self._transport.connect()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/dcerpc/v5/transport.py", line 404, in connect
    self.setup_smb_connection()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/dcerpc/v5/transport.py", line 396, in setup_smb_connection
    self.__smb_connection = SMBConnection(self.getRemoteName(), self.getRemoteHost(), sess_port=self.get_dport(),
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/smbconnection.py", line 78, in __init__
    self.negotiateSession(preferredDialect)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/smbconnection.py", line 114, in negotiateSession
    packet = self.negotiateSessionWildcard(self._myName, self._remoteName, self._remoteHost, self._sess_port,
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/smbconnection.py", line 163, in negotiateSessionWildcard
    self._nmbSession = nmb.NetBIOSTCPSession(myName, remoteName, remoteHost, nmb.TYPE_SERVER, sess_port,
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/nmb.py", line 892, in __init__
    NetBIOSSession.__init__(self, myname, remote_name, remote_host, remote_type=remote_type, sess_port=sess_port,
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/nmb.py", line 752, in __init__
    self._sock = self._setup_connection((remote_host, sess_port), timeout)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/nmb.py", line 904, in _setup_connection
    raise socket.error("Connection error (%s:%s)" % (peer[0], peer[1]), e)
OSError: [Errno Connection error (testdomain.local:445)] [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py", line 142, in __init__
    connection.__init__(self, args, db, host)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/connection.py", line 81, in __init__
    self.proto_flow()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/connection.py", line 118, in proto_flow
    self.call_cmd_args()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/connection.py", line 125, in call_cmd_args
    getattr(self, k)()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/connection.py", line 57, in _decorator
    return func(self, *args, **kwargs)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb.py", line 1381, in users
    users1(self)
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/crackmapextreme-0.1.0-py3.8.egg/cmx/protocols/smb/ENUM/domainenum.py", line 270, in users1
    dce.disconnect()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/dcerpc/v5/rpcrt.py", line 803, in disconnect
    return self._transport.disconnect()
  File "/opt/arocna3/tools/crackmapextreme/.venv/lib/python3.8/site-packages/impacket/dcerpc/v5/transport.py", line 417, in disconnect
    self.__smb_connection.disconnectTree(self.__tid)
AttributeError: 'int' object has no attribute 'disconnectTree'
2020-01-24T20:29:23Z <Greenlet at 0x7fe7027b7ae0: smb(Namespace(all=False, computers=None, content=False, <protocol.database object at 0x7fe7027dabe0>, '192.168.11.18')> failed with AttributeError
`

**Comment by awsmhacks** [comment]
I have that problem when I'm not pointing /etc/resolv.conf  to the internal DNS server.    

it looks up/uses the DC by hostname and i havent figured a way to get the IP of the DC directly in the connection to a host.  
     
so yeah, you can either specify the dc w/ -dc  or set your /etc/resolv.conf to include a nameserver dc.ip.add.ress

i thought of requiring a DC IP for any of the network enum but idk.

**Comment by a-tyler** [comment]
hmm. I am testing on a system where the only two entries in resolv.conf are the DC's and I am still getting that error.
I tested a few methods of getting the DC addr from the targeted host (obviously only if code exec is allowed) and it seems to me that having it run nslookup against itself might be the most efficient (in terms of the amount of usable vs extraneous output).
`cmx smb 192.168.11.114 --local-auth -u administrator -p testpassword -x "nslookup 192.168.11.114"`
Returns:
`Server:  testdomain-DC04.testdomain.local`
`Address:  192.168.11.13`

`Name:    DESKTOP-G8E27KB.testdomain.local`
`Address:  192.168.11.114`

If code exec isn't allowed then the DC can be discovered via DNS with SRV record queries for _gc._tcp.testdomain.local, _ldap._tcp.testdomain.local, and/or _kerberos._tcp.testdomain.local.

As far as requiring a DC IP goes you could maybe not run functions that require the DC if the DC IP isn't known (via command line input or discovered internally)?

If running -recon w/o a known DC IP just exec this:
`sessions,loggedon,ridbrute,disks,shares`
rather than
`sessions,loggedon,ridbrute,disks,shares,local+dom users/groups/computers`

**Comment by a-tyler** [comment]
I threw together something that vaguely resembles a python script (i am weak in the ways of py) to do what I just mentioned.
Dunno if it helps explain the idea or not but I figured it couldnt hurt anything (besides my pride).

[dcLookup.py](https://gist.github.com/a-tyler/2c017d675067cfd8d0fc47b4174db746)

**Comment by a-tyler** [comment]
Going to go ahead and close this issue because the original problem is an issue with impacket (that has been resolved but not officially released) and not cmx.

**Comment by awsmhacks** [comment]
yo yo, I cant reproduce that issue really.  
You have DNS role running/installed on the DC right?  
  
if I have my resolv.conf set to `nameserver dc.ip` (might have to restart networking after change?)  
i can then ping mydomain.tld and the response is the IP of the closest DC.  
  
Here's it not resolving:  
```
(CrackMapExtreme-GMKipJYi) root@ronin:/mnt/hgfs/GitHub/CrackMapExtreme# cat /etc/resolv.conf
nameserver 8.8.8.8
(CrackMapExtreme-GMKipJYi) root@ronin:/mnt/hgfs/GitHub/CrackMapExtreme# ping swamp.local
ping: swamp.local: Name or service not known
```  
then if i add the dc as a nameserver now it will resolve  
```
(CrackMapExtreme-GMKipJYi) root@ronin:/mnt/hgfs/GitHub/CrackMapExtreme# nano /etc/resolv.conf
(CrackMapExtreme-GMKipJYi) root@ronin:/mnt/hgfs/GitHub/CrackMapExtreme# cat /etc/resolv.conf
nameserver 192.168.0.100
nameserver 8.8.8.8
(CrackMapExtreme-GMKipJYi) root@ronin:/mnt/hgfs/GitHub/CrackMapExtreme# ping -c 1 swamp.local
PING swamp.local (192.168.0.100) 56(84) bytes of data.
64 bytes from 192.168.0.100 (192.168.0.100): icmp_seq=1 ttl=128 time=0.573 mss
```   
     
and the netrecon stuff works
