### ISSUE TITLE
CMX Broken On New Versions of Kali Linux

### ISSUE THREAD

**Issue by Ltoolz** [awsmhacks/CrackMapExtreme#26]
**Describe the bug**

<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Traceback (most recent call last):
  File "/usr/local/bin/cmx", line 33, in <module>
    sys.exit(load_entry_point('cmx===0.0.1.azdev1-20201001.101320.43a135c', 'console_scripts', 'cmx')())
  File "/usr/local/bin/cmx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/cmx-0.0.1.azdev1_20201001.101320.43a135c-py3.9.egg/cmx/__init__.py", line 8, in <module>
    monkey.patch_all()
  File "/usr/local/lib/python3.9/dist-packages/gevent/monkey.py", line 1142, in patch_all
    patch_ssl(_warnings=_warnings, _first_time=first_time)
  File "/usr/local/lib/python3.9/dist-packages/gevent/monkey.py", line 183, in ignores
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gevent/monkey.py", line 939, in patch_ssl
    gevent_mod, _ = _patch_module('ssl', _warnings=_warnings)
  File "/usr/local/lib/python3.9/dist-packages/gevent/monkey.py", line 400, in _patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/usr/local/lib/python3.9/dist-packages/gevent/ssl.py", line 32, in <module>
    from gevent import _ssl3 as _source # pragma: no cover
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 171, in <module>
    class SSLSocket(socket):
  File "/usr/local/lib/python3.9/dist-packages/gevent/_ssl3.py", line 184, in SSLSocket
    family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None,
NameError: name 'AF_INET' is not defined
zsh: segmentation fault  cmx

**To Reproduce**
apt install pipenv
cd /opt
git clone https://github.com/awsmhacks/CrackMapExtreme 
cd /opt/CrackMapExtreme  
pipenv --three               #ignore any errors and continue
pipenv shell  
pip install -r requirements.txt 
python setup.py -q install 
cmx
>>> Error 

**Desktop (please complete the following information):**

Python 3.9.0+
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.4
Codename:       kali-rolling

It seems to be a dependency issue from a combination of gevent, azdev1, and panda I believe.

**Comment by awsmhacks** [comment]
Hi, thank you for posting.  
  
I updated the requirements file that should now work with python 3.9.1 on the latest kali.  
You might want to create a new pipenv first, then reinstall.  
Lemme know if you have any issues.

**Comment by Ltoolz** [comment]
ERROR: Could not find a version that satisfies the requirement cmx===0.0.1.azdev1-20201001.101320.43a135c (from -r requirements.txt (line 102)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.11, 0.0.13, 0.0.14)

ERROR: No matching distribution found for cmx===0.0.1.azdev1-20201001.101320.43a135c (from -r requirements.txt (line 102))


Traceback (most recent call last):

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/bin/cmx", line 11, in <module>

    load_entry_point('cmx===0.0.1.azdev1-20210107.121747.873b399', 'console_scripts', 'cmx')()

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point

    return ep.load()

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load

    return self.resolve()

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/root/.local/share/virtualenvs/CrackMapExtreme-GMKipJYi/lib/python3.9/site-packages/cmx-0.0.1.azdev1_20210107.121747.873b399-py3.9.egg/cmx/__init__.py", line 3, in <module>

    from gevent import monkey


ModuleNotFoundError: No module named 'gevent'


Still get errors unfortunately.

**Comment by awsmhacks** [comment]
Yoooo, alright I grabbed a fresh kali.iso. Re-did the requirements.txt file. I think we are good to go now.
Give it a shot and let me know.  
Thanks!

**Comment by Ltoolz** [comment]
You're the man! I appreciate the effort and time you took to figure it all out! Love CMX!

**Comment by Ltoolz** [comment]
Works great
